# Build all production images for a release
# Reads conf/images.yaml to determine what to build

steps:
  # Step 1: Parse build matrix from images.yaml
  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'generate-build-matrix'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        # Install yq for YAML parsing
        wget -qO /usr/local/bin/yq https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64
        chmod +x /usr/local/bin/yq
        
        # Parse production builds from conf/images.yaml
        echo "Parsing conf/images.yaml for production builds..."
        yq eval '.build_matrix.production[] | .machine + ":" + .distro + ":" + .image' conf/images.yaml > /workspace/build-matrix.txt
        
        echo "Production build matrix generated:"
        cat /workspace/build-matrix.txt

  # Step 2: Trigger parallel builds for each configuration
  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'trigger-parallel-builds'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        while IFS=':' read -r machine distro image; do
          echo "Triggering build: $machine / $distro / $image"
          
          gcloud builds submit \
            --config=cloudbuild/build-image.yaml \
            --substitutions="_MACHINE=$machine,_DISTRO=$distro,_IMAGE=$image,_BUILD_VERSION=${_BUILD_VERSION},_BUILD_TYPE=production" \
            --async \
            --no-source
            
        done < /workspace/build-matrix.txt
        
        echo "All builds triggered asynchronously"

  # Step 3: Wait for all builds and generate release manifest
  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'generate-release-manifest'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        # Create release manifest
        cat > release-manifest.json <<EOF
        {
          "version": "${_BUILD_VERSION}",
          "build_id": "$BUILD_ID",
          "build_date": "$(date -u +%Y-%m-%dT%H:%M:%SZ)",
          "git_commit": "$COMMIT_SHA",
          "artifacts_url": "gs://${PROJECT_ID}-yocto-artifacts/production/${_BUILD_VERSION}/",
          "images": [
            $(while IFS=':' read -r machine distro image; do
              echo "{\"machine\": \"$machine\", \"distro\": \"$distro\", \"image\": \"$image\"},"
            done < /workspace/build-matrix.txt | sed '$ s/,$//')
          ]
        }
        EOF
        
        cat release-manifest.json
        
        # Upload to artifacts bucket
        gsutil cp release-manifest.json "gs://${PROJECT_ID}-yocto-artifacts/production/${_BUILD_VERSION}/release-manifest.json"

substitutions:
  _BUILD_VERSION: 'v0.0.0'

timeout: '28800s' # 8 hours for multiple builds
options:
  machineType: 'E2_HIGHCPU_8'
  diskSizeGb: 100
  logging: CLOUD_LOGGING_ONLY
